#!/bin/sh
set -e

case "$1" in
    purge)
        # Удаление конфигурационных файлов
        rm -rf /etc/docker-vulnerability-scanner
        
        # Удаление сервиса
        systemctl disable docker-vulnerability-scanner || true
        rm -f /lib/systemd/system/docker-vulnerability-scanner.service
        systemctl daemon-reload

        # Удаление файлов приложения
        rm -rf /usr/lib/docker-vulnerability-scanner
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0 